//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the framework's tools/build-conditions.ts.
//     Source: the framework's ts/pkjs/wire.ts
//
//     Changes to this file may be lost if the code is regenerated.
//     Edit the source and run `npm run build:conditions` instead.
// </auto-generated>
//------------------------------------------------------------------------------
/**
 * @file wire_caps.g.h
 * @brief Strip caps and marker values shared by the phone and the watch.
 *
 * Generated from the framework's `ts/pkjs/wire.ts`, so the phone and the watch read the same numbers.
 *
 * @ingroup lib_core
 */
#pragma once

#define STOCK_MAX_SLOTS 4 ///< How many tickers the watchlist strip carries
#define STOCK_SYMBOL_LEN 12 ///< A watchlist label, 11 characters plus its terminator

#define CALENDAR_MAX_SLOTS 6 ///< How many events the agenda strip carries
#define CAL_TITLE_LEN 25 ///< An event title, 24 characters plus its terminator
#define CAL_LOC_LEN 17 ///< An event location, 16 characters plus its terminator

#define WEATHER_FORECAST_COLS 8 ///< How many columns a forecast strip carries
#define WEATHER_NO_TEMP -1000 ///< A column with no reading, so the watch draws a placeholder

#define WX_FORECAST_NIGHT_BIT 0x80 ///< Set on an hourly forecast code for a column after dark
