//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the engine's tools/build-conditions.ts.
//     Source: the engine's ts/weather/conditions.ts
//
//     Changes to this file may be lost if the code is regenerated.
//     Edit the source and run `npm run build:conditions` instead.
// </auto-generated>
//------------------------------------------------------------------------------
/**
 * @file icons_table.g.h
 * @brief Condition token to weather icon resource lookup.
 *
 * Generated from the engine's `ts/weather/conditions.ts`, so the phone and the watch read the same numbers.
 *
 * @ingroup lib_ui
 */
#pragma once

/**
 * @brief Finds the icon resource for a condition token.
 *
 * A token ending in `_NIGHT` gets its night glyph where the condition has one.
 * An unknown token, or a NULL one, gets the `WEATHER_NOW_NA` icon.
 *
 * @param condition The condition token from the phone, such as `RAIN` or `RAIN_NIGHT`. May be NULL.
 * @return The `RESOURCE_ID_ICON_*` resource to load.
 *
 * @ingroup lib_ui
 */
static uint32_t wx_resource_for_table(const char *condition)
{
    if (!condition)
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NA;
    }

    if (!strcmp(condition, "CLEAR"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_CLEAR;
    }

    if (!strcmp(condition, "CLEAR_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_CLEAR;
    }

    if (!strcmp(condition, "PCLDY"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_PARTLY_CLOUDY;
    }

    if (!strcmp(condition, "PCLDY_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_PARTLY_CLOUDY;
    }

    if (!strcmp(condition, "CLDY"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_CLOUDY;
    }

    if (!strcmp(condition, "CLDY_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_CLOUDY;
    }

    if (!strcmp(condition, "FOGGY"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_FOG;
    }

    if (!strcmp(condition, "FOGGY_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_FOG;
    }

    if (!strcmp(condition, "DRZL"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_DRIZZLE;
    }

    if (!strcmp(condition, "DRZL_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_DRIZZLE;
    }

    if (!strcmp(condition, "FZDZ"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_SLEET;
    }

    if (!strcmp(condition, "FZDZ_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_SLEET;
    }

    if (!strcmp(condition, "RAIN"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_RAIN;
    }

    if (!strcmp(condition, "RAIN_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_RAIN;
    }

    if (!strcmp(condition, "FZRN"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_SLEET;
    }

    if (!strcmp(condition, "FZRN_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_SLEET;
    }

    if (!strcmp(condition, "SNOW"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_SNOW;
    }

    if (!strcmp(condition, "SNOW_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_SNOW;
    }

    if (!strcmp(condition, "SHWR"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_SHOWERS;
    }

    if (!strcmp(condition, "SHWR_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_SHOWERS;
    }

    if (!strcmp(condition, "SNSH"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_SNOW_WIND;
    }

    if (!strcmp(condition, "SNSH_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_SNOW_WIND;
    }

    if (!strcmp(condition, "STRM"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_THUNDERSTORM;
    }

    if (!strcmp(condition, "STRM_NIGHT"))
    {
        return RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_THUNDERSTORM;
    }

    return RESOURCE_ID_ICON_WEATHER_NOW_NA;
}
