//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the engine's tools/build-conditions.ts.
//     Source: the engine's ts/weather/conditions.ts
//
//     Changes to this file may be lost if the code is regenerated.
//     Edit the source vocabulary and run `npm run build:conditions` instead.
// </auto-generated>
//------------------------------------------------------------------------------
/**
 * @file icon_codes_table.g.h
 * @brief Forecast condition code to weather icon resource lookup.
 *
 * Generated from the engine's `ts/weather/conditions.ts`, so the phone and the watch read the same list.
 *
 * @ingroup lib_ui
 */
#pragma once

#include "ui/weather/icons.h"

/**
 * @brief Finds the icon resource for a forecast condition code.
 *
 * The code is the condition's position in the shared vocabulary, with `WX_FORECAST_NIGHT_BIT`
 * set for an hour after dark. A night hour gets the night glyph where the condition has one.
 * An unknown code, including the 255 the phone sends for a mystery sky, gets the `WEATHER_NOW_NA` icon.
 *
 * @param code The condition code, with the night bit set for an hour after dark.
 * @return The `RESOURCE_ID_ICON_*` resource to load.
 *
 * @ingroup lib_ui
 */
static uint32_t wx_resource_for_code(uint8_t code)
{
    bool night = (code & WX_FORECAST_NIGHT_BIT) != 0;
    switch (code & ~WX_FORECAST_NIGHT_BIT)
    {
    case 0: return night ? RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_CLEAR : RESOURCE_ID_ICON_WEATHER_NOW_CLEAR;
    case 1: return night ? RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_PARTLY_CLOUDY : RESOURCE_ID_ICON_WEATHER_NOW_PARTLY_CLOUDY;
    case 2: return night ? RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_CLOUDY : RESOURCE_ID_ICON_WEATHER_NOW_CLOUDY;
    case 3: return night ? RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_FOG : RESOURCE_ID_ICON_WEATHER_NOW_FOG;
    case 4: return night ? RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_DRIZZLE : RESOURCE_ID_ICON_WEATHER_NOW_DRIZZLE;
    case 5: return night ? RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_SLEET : RESOURCE_ID_ICON_WEATHER_NOW_SLEET;
    case 6: return night ? RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_RAIN : RESOURCE_ID_ICON_WEATHER_NOW_RAIN;
    case 7: return night ? RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_SLEET : RESOURCE_ID_ICON_WEATHER_NOW_SLEET;
    case 8: return night ? RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_SNOW : RESOURCE_ID_ICON_WEATHER_NOW_SNOW;
    case 9: return night ? RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_SHOWERS : RESOURCE_ID_ICON_WEATHER_NOW_SHOWERS;
    case 10: return night ? RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_SNOW_WIND : RESOURCE_ID_ICON_WEATHER_NOW_SNOW_WIND;
    case 11: return night ? RESOURCE_ID_ICON_WEATHER_NOW_NIGHT_THUNDERSTORM : RESOURCE_ID_ICON_WEATHER_NOW_THUNDERSTORM;
    default: return RESOURCE_ID_ICON_WEATHER_NOW_NA;
    }
}
