//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the engine's tools/build-conditions.ts.
//     Source: the engine's ts/weather/conditions.ts
//
//     Changes to this file may be lost if the code is regenerated.
//     Edit the source and run `npm run build:conditions` instead.
// </auto-generated>
//------------------------------------------------------------------------------
/**
 * @file labels_table.g.h
 * @brief Condition token to short and long display label lookups.
 *
 * Generated from the engine's `ts/weather/conditions.ts`, so the phone and the watch read the same numbers.
 *
 * @ingroup lib_ui
 */
#pragma once

#include <string.h>

/**
 * @brief Finds the short display label for a condition token.
 *
 * A `_NIGHT` token reads the same as its day form, so the suffix is dropped before the lookup.
 * An unknown token, or a NULL one, reads "UNKNOWN".
 *
 * @param condition The condition token from the phone, such as `RAIN` or `RAIN_NIGHT`. May be NULL.
 * @return The label, a string literal that stays valid for the life of the app.
 *
 * @ingroup lib_ui
 */
static const char *wx_label_short_for_table(const char *condition)
{
    if (!condition)
    {
        return "UNKNOWN";
    }

    // a night token reuses its day label, so drop a trailing "_NIGHT" before the lookup
    char base[24];
    size_t len = strlen(condition);
    if (len > 6 && !strcmp(condition + len - 6, "_NIGHT"))
    {
        len -= 6;
    }
    if (len >= sizeof(base))
    {
        len = sizeof(base) - 1;
    }
    memcpy(base, condition, len);
    base[len] = '\0';

    if (!strcmp(base, "CLEAR"))
    {
        return "CLEAR";
    }

    if (!strcmp(base, "PCLDY"))
    {
        return "PCLDY";
    }

    if (!strcmp(base, "CLDY"))
    {
        return "CLDY";
    }

    if (!strcmp(base, "FOGGY"))
    {
        return "FOGGY";
    }

    if (!strcmp(base, "DRZL"))
    {
        return "DRZL";
    }

    if (!strcmp(base, "FZDZ"))
    {
        return "FZDZ";
    }

    if (!strcmp(base, "RAIN"))
    {
        return "RAIN";
    }

    if (!strcmp(base, "FZRN"))
    {
        return "FZRN";
    }

    if (!strcmp(base, "SNOW"))
    {
        return "SNOW";
    }

    if (!strcmp(base, "SHWR"))
    {
        return "SHWR";
    }

    if (!strcmp(base, "SNSH"))
    {
        return "SNSH";
    }

    if (!strcmp(base, "STRM"))
    {
        return "STRM";
    }

    return "UNKNOWN";
}

/**
 * @brief Finds the long display label for a condition token.
 *
 * A `_NIGHT` token reads the same as its day form, so the suffix is dropped before the lookup.
 * An unknown token, or a NULL one, reads "Unknown".
 *
 * @param condition The condition token from the phone, such as `RAIN` or `RAIN_NIGHT`. May be NULL.
 * @return The label, a string literal that stays valid for the life of the app.
 *
 * @ingroup lib_ui
 */
static const char *wx_label_long_for_table(const char *condition)
{
    if (!condition)
    {
        return "Unknown";
    }

    // a night token reuses its day label, so drop a trailing "_NIGHT" before the lookup
    char base[24];
    size_t len = strlen(condition);
    if (len > 6 && !strcmp(condition + len - 6, "_NIGHT"))
    {
        len -= 6;
    }
    if (len >= sizeof(base))
    {
        len = sizeof(base) - 1;
    }
    memcpy(base, condition, len);
    base[len] = '\0';

    if (!strcmp(base, "CLEAR"))
    {
        return "Clear";
    }

    if (!strcmp(base, "PCLDY"))
    {
        return "Partly Cloudy";
    }

    if (!strcmp(base, "CLDY"))
    {
        return "Cloudy";
    }

    if (!strcmp(base, "FOGGY"))
    {
        return "Fog";
    }

    if (!strcmp(base, "DRZL"))
    {
        return "Drizzle";
    }

    if (!strcmp(base, "FZDZ"))
    {
        return "Freezing Drizzle";
    }

    if (!strcmp(base, "RAIN"))
    {
        return "Rain";
    }

    if (!strcmp(base, "FZRN"))
    {
        return "Freezing Rain";
    }

    if (!strcmp(base, "SNOW"))
    {
        return "Snow";
    }

    if (!strcmp(base, "SHWR"))
    {
        return "Showers";
    }

    if (!strcmp(base, "SNSH"))
    {
        return "Snow Showers";
    }

    if (!strcmp(base, "STRM"))
    {
        return "Thunderstorm";
    }

    return "Unknown";
}
