/**
 * Specs for the C weather-icon table generator.
 *
 * buildIconsTable is a pure codegen transform: vocabulary in, C source out.
 * A drifted branch or wrong fallback ships a watchface that compiles to the
 * wrong icon (or fails to compile), so the generated shape is pinned here.
 *
 * The last group checks the committed headers instead of the transform. Three things read those
 * files straight from the source tree and none of them run this generator, so a stale commit is
 * invisible until a watch reads a different list from the phone.
 */

import fs from 'node:fs';
import path from 'node:path';
import { describe, test, expect } from 'vitest';
import { buildIconsTable, GENERATED } from './build-conditions';
import vocabulary from '../ts/weather/conditions.ts';
import type { ConditionEntry, ConditionFallback } from '../ts/weather/conditions.ts';

/** The fallback shape conditions.ts really exports: a resource plus both labels. */
const FALLBACK: ConditionFallback = { resource: 'WI_NA', labelShort: 'UNKNOWN', labelLong: 'Unknown' };

/** A fallback on a named resource, for the cases that pin which resource is used. */
function fallbackOf(resource: string): ConditionFallback {
  return { resource: resource, labelShort: 'UNKNOWN', labelLong: 'Unknown' };
}

/** One row, labels defaulted so an icon case only spells out the fields it is about. */
function row(token: string, resource: string, nightResource?: string): ConditionEntry {
  return { token: token, resource: resource, nightResource: nightResource, labelShort: token, labelLong: token };
}

// the forecast wire code is the token's position in conditions.ts, so this order is the contract
// the generated C switch is built against. spelled out literally rather than read back off
// conditions.ts, because a test that works out the expected code from the same array it is
// checking moves with any reorder and can never fail on the drift it is here to catch
const WIRE_CODES: Array<[string, number]> = [
  ['CLEAR', 0],
  ['PCLDY', 1],
  ['CLDY', 2],
  ['FOGGY', 3],
  ['DRZL', 4],
  ['FZDZ', 5],
  ['RAIN', 6],
  ['FZRN', 7],
  ['SNOW', 8],
  ['SHWR', 9],
  ['SNSH', 10],
  ['STRM', 11],
];

/** The code an unrecognized token falls back to, pinned as the wire value the watch decodes. */
const UNKNOWN_WIRE_CODE = 255;

describe('buildIconsTable', () => {
  /** A missing null guard would dereference a null condition string on the watch and crash. */
  test('returns the fallback resource when the condition pointer is null', () => {
    const source = buildIconsTable({
      fallback: FALLBACK,
      conditions: [row('RAIN', 'WI_RAIN')],
    });

    expect(source).toContain('    if (!condition)\n    {\n        return RESOURCE_ID_ICON_WI_NA;\n    }');
  });

  /** A token mapped to the wrong resource silently shows the wrong icon, so the exact branch is pinned. */
  test('emits a strcmp branch mapping each token to its icon resource', () => {
    const source = buildIconsTable({
      fallback: FALLBACK,
      conditions: [row('RAIN', 'WI_RAIN')],
    });

    expect(source).toContain(
      '    if (!strcmp(condition, "RAIN"))\n    {\n        return RESOURCE_ID_ICON_WI_RAIN;\n    }'
    );
  });

  /** Two tokens sharing one glyph (FZDZ/FZRN -> WI_SLEET) must both still get their own branch. */
  test('emits a separate branch for each token even when they share a resource', () => {
    const source = buildIconsTable({
      fallback: FALLBACK,
      conditions: [
        row('FZDZ', 'WI_SLEET'),
        row('FZRN', 'WI_SLEET'),
      ],
    });

    expect(source).toContain('!strcmp(condition, "FZDZ")');
    expect(source).toContain('!strcmp(condition, "FZRN")');
    expect(source.match(/RESOURCE_ID_ICON_WI_SLEET;/g)).toHaveLength(2);
  });

  /** The final unmatched return must use the configured fallback, not a hard-coded one. */
  test('ends the lookup with the configured fallback resource', () => {
    const source = buildIconsTable({
      fallback: fallbackOf('WI_CUSTOM'),
      conditions: [row('RAIN', 'WI_RAIN')],
    });

    expect(source.trimEnd().endsWith('    return RESOURCE_ID_ICON_WI_CUSTOM;\n}')).toBe(true);
  });

  /** The output is a header that gets #included, so it needs the include guard and the do-not-edit banner. */
  test('emits a #pragma once header and the auto-generated banner', () => {
    const source = buildIconsTable({
      fallback: FALLBACK,
      conditions: [row('RAIN', 'WI_RAIN')],
    });

    expect(source).toContain('#pragma once');
    expect(source).toContain('// <auto-generated>');
  });

  /** Every token in the shipped vocabulary must reach the generated table. A dropped one renders WI_NA. */
  test('covers every condition in the real vocabulary', () => {
    const source = buildIconsTable(vocabulary);

    for (const { token, resource } of vocabulary.conditions) {
      expect(source).toContain(`!strcmp(condition, "${token}")`);
      expect(source).toContain(`return RESOURCE_ID_ICON_${resource};`);
    }
  });

  /** The wire carries "<token>_NIGHT" after dark. Without the generated night
   *  branch the watch would fall through to WI_NA and lose the moon glyph. */
  test('emits a _NIGHT branch mapping to the night resource for night-capable rows', () => {
    const source = buildIconsTable({
      fallback: FALLBACK,
      conditions: [row('RAIN', 'WI_RAIN', 'WI_NIGHT_RAIN')],
    });

    expect(source).toContain(
      '    if (!strcmp(condition, "RAIN_NIGHT"))\n    {\n        return RESOURCE_ID_ICON_WI_NIGHT_RAIN;\n    }'
    );
  });

  /** A row with no nightResource must not emit a phantom _NIGHT branch. */
  test('omits the _NIGHT branch when a row has no night resource', () => {
    const source = buildIconsTable({
      fallback: FALLBACK,
      conditions: [row('DUST', 'WI_DUST')],
    });

    expect(source).not.toContain('DUST_NIGHT');
  });

});

describe('codeFor', () => {
  /** The forecast wire code is the array index, so a drift here draws the wrong icon on every column. */
  test.each(WIRE_CODES)('maps %s to wire code %i', (token, expected) => {
    const result = vocabulary.codeFor(token);

    expect(result).toBe(expected);
  });

  /**
   * A watch built against an older vocabulary decodes by position, so inserting or dropping a token
   * renumbers every code after it and draws the wrong sky. Adding one at the end is safe, and the
   * pinned list above is what has to be reviewed to say so.
   */
  test('ships exactly the tokens the pinned wire codes cover, in that order', () => {
    const result = vocabulary.conditions.map((entry) => entry.token);

    expect(result).toEqual(WIRE_CODES.map(([token]) => token));
  });

  /** The forecast shows day glyphs, so a night token must map to the same code as its day form. */
  test('strips the night marker before looking up the code', () => {
    const result = vocabulary.codeFor('RAIN_NIGHT');

    expect(result).toBe(6);
  });

  /** An unknown or empty token must land on UNKNOWN_CODE so the watch draws WI_NA, not a random icon. */
  test.each([['ZZZ'], ['']])('returns UNKNOWN_CODE for an unrecognised or empty token (%s)', (token) => {
    const result = vocabulary.codeFor(token);

    expect(result).toBe(UNKNOWN_WIRE_CODE);
  });
});

describe('the committed headers', () => {
  /**
   * The generated headers are committed because the host C suite compiles `c/core` with plain gcc,
   * Doxygen documents them on a fresh checkout, and an editor resolves the includes from them. None
   * of those run the generator, so an edit to the vocabulary or to WIRE_CAPS that is committed
   * without `npm run build:conditions` leaves the watch bounds-checking against numbers the phone
   * no longer packs to.
   */
  test.each(GENERATED.map((header) => [path.basename(header.out), header] as const))(
    '%s matches what the generator writes now',
    (_name, header) => {
      const result = fs.readFileSync(header.out, 'utf8');

      expect(result).toBe(header.build());
    }
  );
});
