#!/usr/bin/env node
/**
 * Generates the C weather-condition lookups from the shared vocabulary.
 *
 * Reads the framework's ts/weather/conditions.ts and ts/pkjs/wire.ts, the two tables the phone owns,
 * and writes
 *   c/pebble/ui/weather/icons_table.g.h          (token  -> icon resource)
 *   c/pebble/ui/weather/labels_table.g.h         (token  -> short/long display label)
 *   c/core/wire/wire_caps.g.h                    (the strip caps both sides bound against)
 *
 * Each header carries its own Doxygen blocks, so the generated lookups show up in the framework docs
 * like any hand-written file.
 *
 * The headers are committed. The host C suite and Doxygen read them straight from the tree, a face
 * build compiles them as they are, and the spec fails when one no longer matches its source. A header
 * whose contents would not change is left alone.
 *
 * Run via `npm run build:conditions` after editing either source.
 */
import path from 'node:path';
import conditionVocabulary from '../ts/weather/conditions.ts';
import { WIRE_CAPS } from '../ts/pkjs/wire.ts';
import type { ConditionVocabulary } from '../ts/weather/conditions.ts';
import { writeIfChanged } from './files.ts';
import { ENGINE, WORKSPACE } from './paths.ts';

const WEATHER_DIR = path.join(ENGINE, 'c', 'pebble', 'ui', 'weather');
const ICONS_OUT = path.join(WEATHER_DIR, 'icons_table.g.h');
const LABELS_OUT = path.join(WEATHER_DIR, 'labels_table.g.h');
const WIRE_CAPS_OUT = path.join(ENGINE, 'c', 'core', 'wire', 'wire_caps.g.h');

/**
 * The auto-generated banner, the Doxygen file block, and `#pragma once` every emitted header opens
 * with.
 *
 * fileName goes on `@file` and has to match the real file name or Doxygen files the docs under
 * nothing. brief is the one line summary for that file.
 */
function bannerLines(fileName: string, brief: string, source = 'ts/weather/conditions.ts', group = 'lib_ui') {
  return [
    '//------------------------------------------------------------------------------',
    '// <auto-generated>',
    "//     This code was generated by the framework's tools/build-conditions.ts.",
    `//     Source: the framework's ${source}`,
    '//',
    '//     Changes to this file may be lost if the code is regenerated.',
    '//     Edit the source and run `npm run build:conditions` instead.',
    '// </auto-generated>',
    '//------------------------------------------------------------------------------',
    '/**',
    ` * @file ${fileName}`,
    ` * @brief ${brief}`,
    ' *',
    ` * Generated from the framework's \`${source}\`, so the phone and the watch read the same numbers.`,
    ' *',
    ` * @ingroup ${group}`,
    ' */',
    '#pragma once',
    '',
  ];
}

/**
 * Builds the C icon-lookup source from a condition vocabulary.
 *
 * Pure string transform so it can be tested without touching the filesystem.
 * For each condition emits a token -> resource branch, and when the row has a
 * nightResource also emits a "<token>_NIGHT" -> nightResource branch (the wire
 * carries the _NIGHT token after dark).
 *
 * @param vocabulary The fallback icon plus the token/resource rows to build the lookup from.
 * @return The generated C source for icons_table.g.h.
 */
export function buildIconsTable({ fallback, conditions }: ConditionVocabulary) {
  const fallbackResource = `RESOURCE_ID_ICON_${fallback.resource}`;

  const lines = bannerLines('icons_table.g.h', 'Condition token to weather icon resource lookup.');
  lines.push(
    '/**',
    ' * @brief Finds the icon resource for a condition token.',
    ' *',
    ' * A token ending in `_NIGHT` gets its night glyph where the condition has one.',
    ` * An unknown token, or a NULL one, gets the \`${fallback.resource}\` icon.`,
    ' *',
    ' * @param condition The condition token from the phone, such as `RAIN` or `RAIN_NIGHT`. May be NULL.',
    ' * @return The `RESOURCE_ID_ICON_*` resource to load.',
    ' *',
    ' * @ingroup lib_ui',
    ' */',
    'static uint32_t wx_resource_for_table(const char *condition)',
    '{',
    '    if (!condition)',
    '    {',
    `        return ${fallbackResource};`,
    '    }',
    ''
  );

  for (const { token, resource, nightResource } of conditions) {
    lines.push(`    if (!strcmp(condition, "${token}"))`);
    lines.push('    {');
    lines.push(`        return RESOURCE_ID_ICON_${resource};`);
    lines.push('    }');
    lines.push('');

    if (nightResource) {
      lines.push(`    if (!strcmp(condition, "${token}_NIGHT"))`);
      lines.push('    {');
      lines.push(`        return RESOURCE_ID_ICON_${nightResource};`);
      lines.push('    }');
      lines.push('');
    }
  }

  lines.push(`    return ${fallbackResource};`);
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Builds one C label-lookup function (short or long) from the vocabulary.
 *
 * A night token reuses its day label, so the emitted function strips a trailing
 * "_NIGHT" from the input, then does one token -> label branch per condition
 * (half the branches of a day+night table). The suffix strip is a manual tail
 * compare (no strstr, which would pull in a big libc routine). Pure string transform.
 *
 * fnName is the C function name to emit, field is 'labelShort' or 'labelLong',
 * and fallbackText is the label returned for an unrecognized or null token. The
 * field also picks the wording of the emitted doc block.
 */
function buildLabelFn({ conditions }: ConditionVocabulary, fnName: string, field: 'labelShort' | 'labelLong', fallbackText: string) {
  const kind = field === 'labelShort' ? 'short' : 'long';
  const lines = [
    '/**',
    ` * @brief Finds the ${kind} display label for a condition token.`,
    ' *',
    ' * A `_NIGHT` token reads the same as its day form, so the suffix is dropped before the lookup.',
    ` * An unknown token, or a NULL one, reads "${fallbackText}".`,
    ' *',
    ' * @param condition The condition token from the phone, such as `RAIN` or `RAIN_NIGHT`. May be NULL.',
    ' * @return The label, a string literal that stays valid for the life of the app.',
    ' *',
    ' * @ingroup lib_ui',
    ' */',
    `static const char *${fnName}(const char *condition)`,
    '{',
    '    if (!condition)',
    '    {',
    `        return "${fallbackText}";`,
    '    }',
    '',
    '    // a night token reuses its day label, so drop a trailing "_NIGHT" before the lookup',
    '    char base[24];',
    '    size_t len = strlen(condition);',
    '    if (len > 6 && !strcmp(condition + len - 6, "_NIGHT"))',
    '    {',
    '        len -= 6;',
    '    }',
    '    if (len >= sizeof(base))',
    '    {',
    '        len = sizeof(base) - 1;',
    '    }',
    '    memcpy(base, condition, len);',
    "    base[len] = '\\0';",
    '',
  ];

  for (const condition of conditions) {
    const label = condition[field];
    lines.push(`    if (!strcmp(base, "${condition.token}"))`);
    lines.push('    {');
    lines.push(`        return "${label}";`);
    lines.push('    }');
    lines.push('');
  }

  lines.push(`    return "${fallbackText}";`);
  lines.push('}');
  lines.push('');

  return lines;
}

/**
 * Builds the C label-lookup source (both short and long functions).
 *
 * @param vocabulary The fallback labels plus the token/label rows to build the lookups from.
 * @return The generated C source for labels_table.g.h.
 */
export function buildLabelsTable(vocabulary: ConditionVocabulary) {
  const { fallback } = vocabulary;

  const lines = bannerLines('labels_table.g.h', 'Condition token to short and long display label lookups.');
  lines.push('#include <string.h>', '');
  lines.push(...buildLabelFn(vocabulary, 'wx_label_short_for_table', 'labelShort', fallback.labelShort));
  lines.push(...buildLabelFn(vocabulary, 'wx_label_long_for_table', 'labelLong', fallback.labelLong));

  return lines.join('\n');
}

/**
 * Builds the shared wire caps header.
 *
 * Each text cap gains one for the terminator the C buffer has to hold, which is the one place that
 * conversion is written down. The night bit comes from the vocabulary rather than the cap table,
 * because it is a property of the condition code the forecast strip carries.
 *
 * @param caps The cap table from the framework's wire module.
 * @param nightBit The bit the phone sets on an hourly forecast code after dark.
 * @return The full contents of wire_caps.g.h.
 */
export function buildWireCaps(caps: typeof WIRE_CAPS, nightBit: number): string {
  const lines = bannerLines(
    'wire_caps.g.h',
    'Strip caps and marker values shared by the phone and the watch.',
    'ts/pkjs/wire.ts',
    'lib_core'
  );

  const entry = (name: string, value: number | string, brief: string) => {
    lines.push(`#define ${name} ${value} ///< ${brief}`);
  };

  entry('STOCK_MAX_SLOTS', caps.STOCK_MAX_SLOTS, 'How many tickers the watchlist strip carries');
  entry('STOCK_SYMBOL_LEN', caps.STOCK_LABEL_MAX + 1, `A watchlist label, ${caps.STOCK_LABEL_MAX} characters plus its terminator`);
  lines.push('');
  entry('CALENDAR_MAX_SLOTS', caps.CALENDAR_MAX_SLOTS, 'How many events the agenda strip carries');
  entry('CAL_TITLE_LEN', caps.CALENDAR_TITLE_MAX + 1, `An event title, ${caps.CALENDAR_TITLE_MAX} characters plus its terminator`);
  entry('CAL_LOC_LEN', caps.CALENDAR_LOC_MAX + 1, `An event location, ${caps.CALENDAR_LOC_MAX} characters plus its terminator`);
  lines.push('');
  entry('WEATHER_FORECAST_COLS', caps.FORECAST_MAX_COLS, 'How many columns a forecast strip carries');
  entry('WEATHER_NO_TEMP', caps.FORECAST_NO_TEMP, 'A column with no reading, so the watch draws a placeholder');
  lines.push('');
  entry('WX_FORECAST_NIGHT_BIT', `0x${nightBit.toString(16).toUpperCase()}`, 'Set on an hourly forecast code for a column after dark');
  lines.push('');
  entry('SETTINGS_REQUEST_FULL', caps.SETTINGS_REQUEST_FULL, 'A settings request for the watch\'s whole snapshot');
  entry('SETTINGS_REQUEST_FRESH', caps.SETTINGS_REQUEST_FRESH, 'A settings request for only whether the watch booted empty');

  lines.push('');
  return lines.join('\n');
}

/** One header this tool owns: where it lands, and what it should contain right now. */
export interface GeneratedHeader {
  out: string;
  build: () => string;
}

/**
 * Every header this tool writes.
 *
 * `main` writes each one and the spec checks each committed file still matches, so a header added
 * here is covered by both without either being edited. The committed copies are what the host C
 * suite compiles and what Doxygen documents, neither of which runs this generator.
 */
export const GENERATED: GeneratedHeader[] = [
  { out: ICONS_OUT, build: () => buildIconsTable(conditionVocabulary) },
  { out: LABELS_OUT, build: () => buildLabelsTable(conditionVocabulary) },
  { out: WIRE_CAPS_OUT, build: () => buildWireCaps(WIRE_CAPS, conditionVocabulary.FORECAST_NIGHT_BIT) },
];

/** Writes every generated header that changed from its source and logs which ones it wrote. */
function main() {
  const written = GENERATED.filter((header) => writeIfChanged(header.out, header.build()))
    .map((header) => path.relative(WORKSPACE, header.out).split(path.sep).join('/'));

  const count = conditionVocabulary.conditions.length;
  console.log(written.length ? `generated ${written.join(', ')} (${count} conditions)` : `every header already matches (${count} conditions)`);
}

if (import.meta.main) {
  main();
}
